backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "dist/assets/images"
public_folder: "/assets/images"
show_preview_links: True
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    path: "{{year}}/{{month}}/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: blog/{{slug}}
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "New blog" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, add_to_top: false, min: 1, default: ["general"]}
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Content", name: "body", widget: "markdown"}
      - { label: "Date", name: "date", widget: "hidden", default: "git Created"}
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    path: "{{year}}/{{month}}/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: project/{{slug}}
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "New Project" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, add_to_top: false, min: 1, default: ["python"]}
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Content", name: "body", widget: "markdown"}
      - { label: "Date", name: "date", widget: "hidden", default: "git Created"}