backend:
  name: git-gateway
  branch: main
media_folder: "dist/assets/images"
public_folder: "/assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    path: "{{title}}/{{slug}}"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-index"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "New blog" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, add_to_top: false, min: 1, default: ["general"]}
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Content", name: "body", widget: "markdown"}